#!/usr/bin/env python

import json
import requests 
import os 
import argparse

import maskpass

path = os.path.dirname(os.path.abspath(__file__))

DEFAULT_PORT = 3000

DEFAULT_SERVER = f"https://localhost:{DEFAULT_PORT}/"

VERIFY_CERT = path + "/../svp-backend/cert.pem"

class App:
    def __init__(self, server):
        self.server = server

    def run(self):
        menu()

def menu():

    header()

    print("Secure Virtual Pets\n")

    command_list()
    #Prints out initial command list
    while True:

        dec = input('> ')

        dec = dec.rstrip()

        if dec == '1':
            login()
        elif dec == '2': 
            signup() 
        elif dec == 'quit':
            break
        else:
            print("I'm sorry, I didn't recognize that command.")

def login():
    username = input("Username: ");
    password = maskpass.askpass(prompt="Password: ")

    login_payload = {"password": password, "username": username } 
    login_payload = json.dumps(login_payload)
    # gonna have to fix this in a real networking-orinented way
    print(requests.post(server + 'auth/login', verify=VERIFY_CERT, data=login_payload))
    pass


def signup():
    email = input("Your Email: ");
    username = input("Username: ");
    password = maskpass.askpass(prompt="Password: ")

    signup_payload = { "email": email ,   "password": password, "username": username } 
    signup_payload = json.dumps(signup_payload)
    
    print(server + 'auth/signup')
    response = requests.post(server + 'auth/signup', verify=VERIFY_CERT, data=signup_payload)

    print(response)

def header():
    print(r"""
 $$$$$$\  $$\    $$\ $$$$$$$\  
$$  __$$\ $$ |   $$ |$$  __$$\ 
$$ /  \__|$$ |   $$ |$$ |  $$ |
\$$$$$$\  \$$\  $$  |$$$$$$$  |
 \____$$\  \$$\$$  / $$  ____/ 
$$\   $$ |  \$$$  /  $$ |      
\$$$$$$  |   \$  /   $$ |      
 \______/     \_/    \__|      
 """)
                               
#header. Prints the nice header. ASCII art generated by patorjk's TAAG

def command_list():
    print("""
    [\033[32m1\033[0m] : Login
    [\033[32m2\033[0m] : Signup 
    quit : close the program
    """)

if __name__ == "__main__": 
    parser = argparse.ArgumentParser(description="Secure Virtual Pets")
    parser.add_argument("--server", default=DEFAULT_SERVER, help="Server URL")
    args = parser.parse_args()
    server = args.server
    app = App(server)
    app.run()
